//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.10.04 at 05:00:25 PM CEST
//
package org.modelio.module.attacktreedesigner.conversion.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for attackTreeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="attackTreeType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="treeDiagram" type="{}treeDiagramType"/>
 * &lt;element name="attack" type="{}attackType"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "attackTreeType", propOrder = {
    "treeDiagram",
    "attack"
})
@XmlRootElement(name="attackTree")
public class AttackTreeType {
    @XmlElement(required = true)
    protected TreeDiagramType treeDiagram;

    @XmlElement(required = true)
    protected AttackType attack;

    /**
     * Gets the value of the treeDiagram property.
     * @return
     * possible object is
     * {@link TreeDiagramType }
     */
    public TreeDiagramType getTreeDiagram() {
        return this.treeDiagram;
    }

    /**
     * Sets the value of the treeDiagram property.
     * 
     * @param value allowed object is
     * {@link TreeDiagramType }
     */
    public void setTreeDiagram(TreeDiagramType value) {
        this.treeDiagram = value;
    }

    /**
     * Gets the value of the attack property.
     * @return
     * possible object is
     * {@link AttackType }
     */
    public AttackType getAttack() {
        return this.attack;
    }

    /**
     * Sets the value of the attack property.
     * 
     * @param value allowed object is
     * {@link AttackType }
     */
    public void setAttack(AttackType value) {
        this.attack = value;
    }

}
