//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.10.04 at 05:00:25 PM CEST
//
package org.modelio.module.attacktreedesigner.conversion.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for operatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="operatorType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;choice maxOccurs="unbounded" minOccurs="0">
 * &lt;element name="attack" type="{}attackType"/>
 * &lt;element name="treeReference" type="{}treeReferenceType"/>
 * &lt;element name="operator" type="{}operatorType"/>
 * &lt;/choice>
 * &lt;/sequence>
 * &lt;attribute name="type" use="required" type="{}operationType" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "operatorType", propOrder = {
    "attackOrTreeReferenceOrOperator"
})
public class OperatorType {
    @XmlAttribute(name = "type", required = true)
    protected OperationType type;

    @XmlElements({
        @XmlElement(name = "attack", type = AttackType.class),
        @XmlElement(name = "treeReference", type = TreeReferenceType.class),
        @XmlElement(name = "operator", type = OperatorType.class)
    })
    protected List<Object> attackOrTreeReferenceOrOperator;

    /**
     * Gets the value of the type property.
     * @return
     * possible object is
     * {@link OperationType }
     */
    public OperationType getType() {
        return this.type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value allowed object is
     * {@link OperationType }
     */
    public void setType(OperationType value) {
        this.type = value;
    }

    /**
     * Gets the value of the attackOrTreeReferenceOrOperator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attackOrTreeReferenceOrOperator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getAttackOrTreeReferenceOrOperator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttackType }
     * {@link TreeReferenceType }
     * {@link OperatorType }
     */
    public List<Object> getAttackOrTreeReferenceOrOperator() {
        if (this.attackOrTreeReferenceOrOperator == null) {
            this.attackOrTreeReferenceOrOperator = new ArrayList<>();
        }
        return this.attackOrTreeReferenceOrOperator;
    }

}
